version: '3.7'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker
    volumes:
      - .:/app

  celery_worker:
    build: .
    container_name: celery_worker
    command: poetry run celery -A app.celery_config worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"